### ISSUE TITLE
Upgrading to Rails 5

### ISSUE THREAD

**Issue by tarujain20** [aptible/aptible-auth-ruby#56]
Upgrading to Rails 5 is failing because:

aptible-api (>= 0) ruby depends on
      aptible-auth (>= 0.5.0) ruby depends on
        activesupport (~> 4.0) ruby

Is there any fork/fix for apitble-auth that uses activesupport > 4.0

**Comment by aaronchi** [comment]
The latest version no longer relies on activesupport
