### ISSUE TITLE
Remove oauth2 gem dependency

### ISSUE THREAD

**Issue by fancyremarker** [aptible/aptible-auth-ruby#7]
The forked gem is a pain, and it's easy enough to construct requests without it.

We should also add integration tests to auth.aptible.com when we do this.

**Comment by 97jaz** [comment]
Is the forked gem even necessary any longer? Both of the issued mentioned appear to have been resolved. (I ask, because I'd like to use the api gem from within a Ruby application, rather than calling out to the CLI, but dependencies are a bit of a problem right now.)

**Comment by aaronchi** [comment]
Resolved by #67
